gui:
  theme:
    lightTheme: true
    selectedLineBgColor:
      - reverse
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - yellow
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --24-bit-color=never
